class FairLocation {
  final String name;
  final String venue;
  final double latitude;
  final double longitude;
  final double radius; // in meters
  final int points;
  final String description;

  const FairLocation({
    required this.name,
    required this.venue,
    required this.latitude,
    required this.longitude,
    required this.radius,
    required this.points,
    required this.description,
  });
}

/// Three career fair locations across Selangor / KL region
const List<FairLocation> kCareerFairs = [
  FairLocation(
    name: 'KL Career Expo 2026',
    venue: 'Kuala Lumpur Convention Centre',
    latitude: 3.1570,
    longitude: 101.7110,
    radius: 300,
    points: 50,
    description: 'Annual flagship career expo featuring 200+ employers',
  ),
  FairLocation(
    name: 'Shah Alam Job Fair',
    venue: 'SACC Convention Centre',
    latitude: 3.0738,
    longitude: 101.5183,
    radius: 300,
    points: 30,
    description: 'State-level job fair focused on manufacturing & tech sectors',
  ),
  FairLocation(
    name: 'Subang Education Fair',
    venue: 'Subang Parade Exhibition Hall',
    latitude: 3.0791,
    longitude: 101.5800,
    radius: 300,
    points: 20,
    description: 'Education and internship fair for students & fresh grads',
  ),
  FairLocation(
    name: 'Universiti Teknologi Malaysia (UTM) Johor Bahru Campus Education Fair',
    venue: 'Dewan Sultan Iskandar (Sultan Iskandar Hall)',
    latitude: 1.5558,
    longitude: 103.6434,
    radius: 600,
    points: 20,
    description: 'Education and internship fair for students & fresh grads',
  ),
  FairLocation(
    name: 'Danga Bay Convention Hall Education Fair',
    venue: 'Danga Bay Convention Centre',
    latitude: 1.4651716,
    longitude: 103.7273141,
    radius: 350,
    points: 40,
    description: 'Career and education fair featuring universities, training providers, and industry exhibitors offering study pathways, internships, and job opportunities',
  ),
  FairLocation(
    name: 'Mid Valley Southkey Education Fair',
    venue: 'Mid Valley Exhibition Centre Johor Bahru',
    latitude: 1.5013,
    longitude: 103.7774,
    radius: 600,
    points: 20,
    description: 'Education and internship fair for students & fresh grads',
  ),
  FairLocation(
    name: 'Southern University College Education Fair',
    venue: 'Dato\' Seri Joseph Chong Multipurpose Hall',
    latitude: 1.5336,
    longitude: 103.6819,
    radius: 600,
    points: 20,
    description: 'Education and internship fair for students & fresh grads',
  ),
  FairLocation(
    name: 'MYCareerFair @ IOI City Mall',
    venue: 'IOI City Mall Grand Exhibition Centre',
    latitude: 2.9696,
    longitude: 101.7133,
    radius: 300,
    points: 50,
    description: 'Large-scale national career & education fair with employers and universities',
  ),
  FairLocation(
    name: 'Malaysia Career & Training Fair (MCTF)',
    venue: 'Mid Valley Exhibition Centre Kuala Lumpur',
    latitude: 3.1175,
    longitude: 101.6769,
    radius: 300,
    points: 40,
    description: 'One of Malaysia’s largest career fairs with 100+ employers and job opportunities',
  ),
  FairLocation(
    name: 'Talentbank Career Fair @ Sunway Pyramid',
    venue: 'Sunway Pyramid Convention Centre',
    latitude: 3.0733,
    longitude: 101.6072,
    radius: 300,
    points: 40,
    description: 'Popular career discovery event connecting graduates with top employers',
  ),
  FairLocation(
    name: 'National Career Fair @ MITEC',
    venue: 'Malaysia International Trade and Exhibition Centre (MITEC)',
    latitude: 3.1700,
    longitude: 101.6650,
    radius: 400,
    points: 50,
    description: 'Large national-level career fair with shuttle access and major employers حضور',
  ),
  FairLocation(
    name: 'Mega Careers & Study Fair (MCASF)',
    venue: 'Kuala Lumpur Convention Centre',
    latitude: 3.1579,
    longitude: 101.7123,
    radius: 300,
    points: 45,
    description: 'Career and postgraduate study fair with internships, jobs, and university booths',
  ),
  FairLocation(
    name: 'MITEC Mega Career Fair',
    venue: 'Malaysia International Trade and Exhibition Centre (MITEC)',
    latitude: 3.1791,
    longitude: 101.6682,
    radius: 400,
    points: 50,
    description: 'Large-scale national career fair with thousands of вакансии and major employers المشاركة',
  ),
  FairLocation(
    name: 'Mid Valley Career & Training Fair',
    venue: 'Mid Valley Exhibition Centre (MVEC)',
    latitude: 3.1176,
    longitude: 101.6782,
    radius: 300,
    points: 45,
    description: 'Well-established career fair with 100+ employers and resume workshops',
  ),
  FairLocation(
    name: 'Bukit Jalil Career Discovery Fair',
    venue: 'Pavilion Bukit Jalil Exhibition Centre',
    latitude: 3.0522,
    longitude: 101.6698,
    radius: 300,
    points: 35,
    description: 'Modern mall-based career fair targeting young professionals and fresh grads',
  ),
  FairLocation(
    name: 'The Mines Job & Education Expo',
    venue: 'Mines International Exhibition & Convention Centre (MIECC)',
    latitude: 3.0298,
    longitude: 101.7182,
    radius: 350,
    points: 35,
    description: 'Regional expo combining job opportunities and education pathways',
  ),
  FairLocation(
    name: 'MATRADE Career & Industry Fair',
    venue: 'MATRADE Exhibition & Convention Centre',
    latitude: 3.1773,
    longitude: 101.6669,
    radius: 350,
    points: 40,
    description: 'Industry-focused career fair with export, business, and trade companies',
  ),
];
